## Importing Packages 

In [8]:
import pandas as pd 
import numpy as np
from sklearn.preprocessing import LabelEncoder # label encoder is to encode the data 

In [9]:
import pandas as pd
import numpy as np

In [10]:
dataset = pd.read_csv('datasets/flower.csv')

In [11]:
dataset

Dataset order  Sepal length  Sepal width  Petal length  Petal width  \
0                1           5.1          3.5           1.4          0.2   
1                2           4.9          3.0           1.4          0.2   
2                3           4.7          3.2           1.3          0.2   
3                4           4.6          3.1           1.5          0.2   
4                5           5.0          3.6           1.4          0.3   
..             ...           ...          ...           ...          ...   
145            146           6.7          3.0           5.2          2.3   
146            147           6.3          2.5           5.0          1.9   
147            148           6.5          3.0           5.2          2.0   
148            149           6.2          3.4           5.4          2.3   
149            150           5.9          3.0           5.1          1.8   

          Species  
0       I.�setosa  
1       I.�setosa  
2       I.�setosa  
3       I.�setosa  
4       I.�setosa  
..            ...  
145  I.�virginica  
146  I.�virginica  
147  I.�virginica  
148  I.�virginica  
149  I.�virginica  

[150 rows x 6 columns]

In [12]:
dataset.head() # head is used to display 5 rows of a dataset

Dataset order  Sepal length  Sepal width  Petal length  Petal width  \
0              1           5.1          3.5           1.4          0.2   
1              2           4.9          3.0           1.4          0.2   
2              3           4.7          3.2           1.3          0.2   
3              4           4.6          3.1           1.5          0.2   
4              5           5.0          3.6           1.4          0.3   

     Species  
0  I.�setosa  
1  I.�setosa  
2  I.�setosa  
3  I.�setosa  
4  I.�setosa

## Converting dataset into numeric form

In [13]:
#breaking into x and y 
x = dataset.iloc[:,1:5].values

In [14]:
x

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.3],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [15]:
y = dataset.iloc[:,5] # y is dependent variable but y is not converting into numeric form

In [16]:
y

0         I.�setosa
1         I.�setosa
2         I.�setosa
3         I.�setosa
4         I.�setosa
           ...     
145    I.�virginica
146    I.�virginica
147    I.�virginica
148    I.�virginica
149    I.�virginica
Name: Species, Length: 150, dtype: object

In [17]:
y = dataset.iloc[:,5].values

In [18]:
labelencoder_y = LabelEncoder()
y = labelencoder_y.fit_transform(y) 

In [19]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size = 0.2)  #0.2 = 20%

In [20]:
len(x_train),len(x_test),len(y_train),len(y_test)

(120, 30, 120, 30)

## Logistic Regression

In [21]:
from sklearn.linear_model import LogisticRegression
logmodel = LogisticRegression()
logmodel.fit(x_train,y_train)

/usr/local/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [22]:
y_pred = logmodel.predict(x_test)

In [23]:
y_pred

array([2, 1, 1, 1, 2, 1, 2, 1, 2, 2, 0, 0, 2, 1, 1, 0, 0, 1, 1, 2, 1, 1,
       0, 0, 0, 1, 2, 2, 0, 0])

In [24]:
y_test

array([2, 1, 2, 1, 2, 1, 2, 2, 2, 2, 0, 0, 2, 1, 1, 0, 0, 1, 1, 2, 2, 1,
       0, 0, 0, 1, 2, 2, 0, 0])

## To check the prediction is correct or not.

In [25]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,y_pred)

array([[9, 0, 0],
       [0, 9, 0],
       [0, 3, 9]])

In [26]:
29/30 # 9+8+12 / (sum of all) 30 which is 0.9666666666666667 = 96% aqurate

0.9666666666666667

## KNeighborsClassifier Algo

In [27]:
from sklearn.neighbors import KNeighborsClassifier
classifier_knn = KNeighborsClassifier(n_neighbors=5,metric = 'minkowski', p = 2) # (minkowski -- (mathematician))
classifier_knn.fit(x_train,y_train)

KNeighborsClassifier()

In [ ]:
y_pred = classifier_knn.predict(x_test)

In [ ]:
confusion_matrix(y_test,y_pred)

## naive_bayes

In [ ]:
from sklearn.naive_bayes import GaussianNB
classifier_nb = GaussianNB()
classifier_nb.fit(x_train,y_train)

In [ ]:
y_pred = classifier_nb.predict(x_test)

In [ ]:
confusion_matrix(y_test,y_pred)

## Support Vector Machine

In [ ]:
from sklearn.svm import SVC
classifier_svm_sigmoid = SVC(kernel = 'sigmoid')
classifier_svm_sigmoid.fit(x_train,y_train)


In [ ]:
y_pred = classifier_svm_sigmoid.predict(x_test)

In [ ]:
confusion_matrix(y_test,y_pred)

In [ ]:
from sklearn.svm import SVC
classifier_svm_linear = SVC(kernel = 'linear')
classifier_svm_linear.fit(x_train,y_train)

In [ ]:
y_pred = classifier_svm_linear.predict(x_test)

In [ ]:
confusion_matrix(y_test,y_pred)

In [ ]:
from sklearn.svm import SVC
classifier_svm_rdf = SVC(kernel = 'rbf')
classifier_svm_rdf.fit(x_train,y_train)

In [ ]:
y_pred = classifier_svm_rdf.predict(x_test)

In [ ]:
confusion_matrix(y_test,y_pred)

In [ ]:
from sklearn.svm import SVC
classifier_svm_poly = SVC(kernel = 'poly')
classifier_svm_poly.fit(x_train,y_train)

In [ ]:
y_pred = classifier_svm_poly.predict(x_test)

In [ ]:
confusion_matrix(y_test,y_pred)

## Decision Tree 

In [ ]:
from sklearn.tree import DecisionTreeClassifier
classifier_dt = DecisionTreeClassifier(criterion = 'entropy') # Entropy decides the impurity is larger than data or not (idealy it is to be less)
classifier_dt.fit(x_train,y_train)

In [ ]:
y_pred = classifier_dt.predict(x_test)

In [ ]:
confusion_matrix(y_test,y_pred)

## Random Forest Classifier

In [ ]:
from sklearn.ensemble import RandomForestClassifier # ensemble learning is that if 1 model runs into another model (Decision tree run in Random forest so this is called ensemble learning)
classifier_rf = RandomForestClassifier(n_estimators = 3, criterion = 'entropy') # n_estimators means how many times do you want to run decision tree
classifier_rf.fit(x_train,y_train)

In [ ]:
y_pred = classifier_rf.predict(x_test)

In [ ]:
confusion_matrix(y_test,y_pred)

In [ ]:
from sklearn.linear_model import LinearRegression

In [ ]:
lin_reg = LinearRegression()
lin_reg.fit(x_train,y_train)

In [ ]:
from sklearn.metrics import mean_squared_error

In [ ]:
y_pred = lin_reg.predict(x_test)

In [ ]:
lin_mse = mean_squared_error(y_test,y_pred)

In [ ]:
lin_mse

In [ ]:
np.sqrt(lin_mse)